### ISSUE TITLE
Still error when update new version fix/upgrade-v0_1_2

### ISSUE THREAD

**Issue by vietnnit** [Galactica-corp/galactica#4]
I had pull the fix/upgrade-v0_1_2 version but still get error.
On previos v.0.1.1 and  fix/upgrade-v0_1_2 I still get the "Error: post failed: Post "http://localhost:46657": dial tcp 127.0.0.1:46657: connect: connection refused"
![galactica](https://github.com/Galactica-corp/galactica/assets/10219011/c6263dc3-a4bc-4f51-b019-c5f67899bb6e)

**Comment by jilio** [comment]
Hi @vietnnit 
Thank you for your interest in Galactica. Please wait until we complete testing and release an official fix, which will include detailed instructions. This issue will be resolved once more than half of all validators are running the fixed node.

**Comment by vietnnit** [comment]
How do I will be the first when the update is released?
Thanks!

**Comment by vietnnit** [comment]
When I igore sync 
"galacticad tendermint unsafe-reset-all --home $HOME/.galactica
if curl -s --head curl https://testnet-files.itrocket.net/galactica/snap_galactica.tar.lz4 | head -n 1 | grep "200" > /dev/null; then
  curl https://testnet-files.itrocket.net/galactica/snap_galactica.tar.lz4 | lz4 -dc - | tar -xf - -C $HOME/.galactica
    else
  echo no have snap
fi"
and do 
sudo systemctl stop galacticad

cp $HOME/.galactica/data/priv_validator_state.json $HOME/.galactica/priv_validator_state.json.backup

rm -rf $HOME/.galactica/data $HOME/.galactica/wasmPath
curl https://testnet-files.itrocket.net/galactica/snap_galactica.tar.lz4 | lz4 -dc - | tar -xf - -C $HOME/.galactica

mv $HOME/.galactica/priv_validator_state.json.backup $HOME/.galactica/data/priv_validator_state.json

sudo systemctl restart galacticad && sudo journalctl -u galacticad -f
Everything all done.
But if I do manual sync
sudo systemctl stop althea

cp $HOME/.althea/data/priv_validator_state.json $HOME/.althea/priv_validator_state.json.backup
althea tendermint unsafe-reset-all --home $HOME/.althea

peers="6e1396c306d2d7f41dc199b16ecff2fd914eaa15@althea-testnet-peer.itrocket.net:19656,9089761d15a04406d7edf2dd5723a6a46831f16e@116.202.227.117:15256,e36803b3439d680eea4ff9c7b3b21d44629e6952@161.97.173.28:26656,ba10cd095e9943e3aec54c1f32de09dd357aa3b3@142.132.202.92:31756,b8fe8a1fee36142b4c569ea7b3a03c10bfc9170b@[2a01:4f8:10a:45d5::2]:26656,cfa7ebb652c4e7602766d4be389be9aa02c1474b@217.76.49.139:31556,44bbdf571faf963bcdc7f8693c4ad5e57394111f@[2a01:4f9:3b:2161::2]:27656,3b4f15d5c9860e731380e4df3c895a1b8a6bc297@173.249.59.70:30656,30025628cbcf5eb4d36aaba979f999eabefbc601@38.242.136.246:30656,f070313cfac9f3ebc902f2ec50ae619ec0a82678@185.119.116.232:26656,57d7a8ed61edbef8dd554fae5ca1a1d205e0374a@[2a01:4f8:a0:9062::2]:26757"  
SNAP_RPC="https://althea-testnet-rpc.itrocket.net:443"

sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$peers\"/" $HOME/.althea/config/config.toml 

LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height);
BLOCK_HEIGHT=$((LATEST_HEIGHT - 1000));
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash) 

echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH && sleep 2

sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ;
s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ;
s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ;
s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"| ;
s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"\"|" $HOME/.althea/config/config.toml

mv $HOME/.althea/priv_validator_state.json.backup $HOME/.althea/data/priv_validator_state.json

sudo systemctl restart althea && sudo journalctl -u althea -f
I caugh caught error!
I think old snapshot had some erorrs!
Thanks!

**Comment by yakud** [comment]
@vietnnit you can find the guide for upgrading from v0.1.1 to v0.1.2 there:

https://github.com/Galactica-corp/galactica/blob/master/app/upgrades/v0_1_2/README.md

**Comment by yakud** [comment]
Just in case the errors like:
```
ERR CONSENSUS FAILURE!!! err="failed to apply block; error commit failed for application: error changing validator set: duplicate entry Validator{780F721A01FFFDBCA77F81174BBC5C7F2CA139EA PubKeyEd25519{BE56AD0FDC7B31A227C6CEEC0F35D5AE2F118D7603380B8347AA4211881F701F} VP:132900 A:0} in
```
this is normal behavior. The validator will proceed to work when more than half of the participants have updated to the latest version.

**Comment by vietnnit** [comment]
Auto sync block :)
Thanks!
